### PR TITLE
Added build-guide and updated link to latest version (1.6.0)

### PR DESCRIPTION
**Pull request by rkapl123**
Dear Govert, Augusto!

I've started a small guide for building Excel-DNA (to be completed) and updated the latest version of Excel-DNA.

-regards,
Roland

### CODE REVIEW

**Comment by govert** [comment]
@rkapl123 Thank you for updating this. We have started putting the various documentations into a cleaned up web site, and will include your changes and additions from here.

@sagishahar Can you check that we use the two files from this branch, instead of the master?

**Comment by rkapl123** [comment]
Dear Govert!

I've added your hint to the guide-for-building.md

**Comment by rkapl123** [comment]
Dear govert!Thanks for pointing out this new documentation, how will we then contribute to this?Regards, Roland Am 28.12.2022 um 21:42 schrieb Govert van Drimmelen ***@***.***>:﻿
@rkapl123 Thank you for updating this. We have started putting the various documentations into a cleaned up web site, and will include your changes and additions from here.
@sagishahar Can you check that we use the two files from this branch, instead of the master?

**Comment by govert** [comment]
> how will we then contribute to this?

Thank you for your interest and contributions @rkapl123 
It's been long overdue to make an updated single website, and I've struggled to get a plan and work on it myself, but I have a bit of ongoing help now. Once we have a consolidated site in place, I think we'll make it public for contribution again.

**Pull request merged**
