### PR TITLE
enhanced com-server-support documentation

### PR DESCRIPTION
**Pull request by rkapl123**
Hi Augusto!

As I didn't know this exactly (and had it working before), I added the documentation for adding a com server (including a late bound object creation) into the relevant doc. I also added an example zip to quickly start writing com servers.

Additionally I added a Datepicker replacement for people that want to use this in a 64 bit environment.

### CODE REVIEW

**Review by augustoproiete — CHANGES_REQUESTED** [review]
Thanks @rkapl123 this looks good!

I think the contents of the `COMAddin.zip` would be a better fit as plain-text files in the [Samples](https://github.com/Excel-DNA/Samples) repository, and we can leave this repo for docs only.

In doing that:
- Let's remove the `ComAddin.csproj.user` from both folders file as these are settings specific to you/your machine
- I think it would better to remove the `Tester.xlsm` file and replace with instructions on how to test the addin, as asking users to download a file with macros would introduce more security risks - i.e. although I know I can trust you, it's hard to guarantee that you don't have any malware in your computer that you're unaware of, so hard to make sure that it's safe to open the file - @govert what do you think?

**Comment by rkapl123** [comment]
Hi augusto!
Sorry for not having a look at the Samles repo, if I had looked at it earlier I wouldn't have spent so much time on the cs example (actually none at all, as there are already two! samples). I've removed the user project settings and will add the VB version of the COM Server example, if thats ok. The excel is not really needed as the test procedure is fairly simple.

**Comment by augustoproiete** [comment]
@rkapl123 Perfect! Let me know when you push these changes to this PR

**Comment by rkapl123** [comment]
OK, I've removed the zip and added a reference to the Samples repo (where I also made a pull request).

**Review by augustoproiete — APPROVED** [review]
LGTM! Thanks @rkapl123

**Comment by govert** [comment]
Thank you Roland! (And @augustoproiete)

**Pull request merged**
