### PR TITLE
enhancements

### PR DESCRIPTION
**Pull request by rkapl123**
added goverts youtube videos to header
added a nice function example to main page
enhanced ribbon-customization documentation with extensive example and some hints.

### CODE REVIEW

**Comment by govert** [comment]
Thanks Roland. Over time I think we'll need to consolidate the docs here, the Samples repo, and the Tutorials repo where I have put the stuff behind the YouTube videos.
I think for now, the best plan is to have code snippets and projects go into the samples repo, and have the docs point to the relevant snippet or project there. So maybe the ribbon sample code that you've added inline here can go into the samples repo, either as a separate project that would compile, or just a loose file in the Misc directory. But I'm open to other suggestions - what do you think?

**Comment by rkapl123** [comment]
You're probably right, as the example is way too long for such a short introduction to the topic. Actually we should just refer to the Samples and Tutorials from there and let the people decide what they are most interested in. I just had in mind sharing some advanced ribbon techniques in VB, so I'll create a RibbonVB project in the Samples repo. Probably it will overlap a bit with your tutorial, which is also VB, but as long as you are not going into too much depth there, it will still add some value to VB people.

**Comment by govert** [comment]
@rkapl123 That would be great. I think another VB ribbon sample would be helpful, especially as you're showing some other stuff beyond the basics.

**Comment by rkapl123** [comment]
OK, I removed the code and added a RibbonVB project in the Samples Repo.
I have still to finish that as it is derived from my DB Addin and I just want to focus on the Ribbon/UI related topics from there.

**Comment by rkapl123** [comment]
So, the RibbonVB Sample project is finished, is there anything left?

**Comment by govert** [comment]
Thanks Roland! If you want to add a pointer to the CustomXML sample too, that would be great.

**Pull request merged**
